<template>
  <h-single-layout>
    <h-transform
      left-title="JSON 输入"
      right-title="Go Struct"
      input-lang="json"
      output-lang="go"
      :sample-data="sample"
      :input-handler="convertFn"
    />
  </h-single-layout>
</template>

<script setup lang="ts">
const sample = `{
  "name": "SuperTools",
  "version": "1.0.0",
  "isOpenSource": true,
  "downloads": 10000,
  "tags": ["electron", "vue"],
  "author": {
    "name": "Dev",
    "email": "dev@example.com"
  }
}`

function goType(value: unknown): string {
  if (value === null) return 'interface{}'
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]interface{}'
    return `[]${goType(value[0])}`
  }
  switch (typeof value) {
    case 'string': return 'string'
    case 'number': return Number.isInteger(value) ? 'int' : 'float64'
    case 'boolean': return 'bool'
    case 'object': return 'AutoGenerated'
    default: return 'interface{}'
  }
}

function jsonToGo(obj: Record<string, unknown>, structName: string, depth = 0): string {
  const fields: string[] = []
  const nested: string[] = []

  for (const [key, value] of Object.entries(obj)) {
    const goName = capitalize(key)
    const jsonTag = `\`json:"${key}"\``

    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      const nestedName = depth === 0 ? capitalize(key) : `${structName}${capitalize(key)}`
      nested.push(jsonToGo(value as Record<string, unknown>, nestedName, depth + 1))
      fields.push(`\t${goName} ${nestedName} ${jsonTag}`)
    } else if (Array.isArray(value) && value.length > 0 && typeof value[0] === 'object' && value[0] !== null) {
      const nestedName = depth === 0 ? capitalize(key) : `${structName}${capitalize(key)}`
      nested.push(jsonToGo(value[0] as Record<string, unknown>, nestedName, depth + 1))
      fields.push(`\t${goName} []${nestedName} ${jsonTag}`)
    } else {
      fields.push(`\t${goName} ${goType(value)} ${jsonTag}`)
    }
  }

  const structStr = `type ${structName} struct {\n${fields.join('\n')}\n}`
  return nested.length > 0 ? `${nested.join('\n\n')}\n\n${structStr}` : structStr
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function convertFn(input: string): string {
  try {
    const parsed = JSON.parse(input)
    if (typeof parsed !== 'object' || parsed === null) {
      return 'Error: 输入必须是 JSON 对象或数组'
    }
    if (Array.isArray(parsed)) {
      if (parsed.length === 0) return 'type AutoGenerated []interface{}'
      const first = parsed[0]
      if (typeof first === 'object' && first !== null) {
        const struct = jsonToGo(first as Record<string, unknown>, 'AutoGeneratedItem')
        return struct + '\n\ntype AutoGenerated []AutoGeneratedItem'
      }
      return `type AutoGenerated []${goType(first)}`
    }
    return jsonToGo(parsed as Record<string, unknown>, 'AutoGenerated')
  } catch (err) {
    return `❌ JSON 格式错误: ${(err as Error).message}`
  }
}
</script>
